version: 2

project_name: nimbopacks

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/nimbopacks
    binary: nimbopacks
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    files:
      - LICENSE

checksum:
  name_template: checksums.txt
  algorithm: sha256

sboms:
  - artifacts: archive
  - artifacts: binary

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*feat(\(.+\))?!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*fix(\(.+\))?!?:.+$'
      order: 1
    - title: Other Changes
      order: 999
  filters:
    exclude:
      - '^docs(\(.+\))?:'
      - '^chore(\(.+\))?:'
      - '^ci(\(.+\))?:'

snapshot:
  version_template: "{{ incpatch .Version }}-next"
